[package]
name = "oxeylyzer-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-ws = "0.2.5"
actix-rt = "2.9.0"
pkg-config = "0.3.27"
tokio = {version = "1", features = ["full"]}
